## https://golangci-lint.run/usage/configuration/

run:
  timeout: 1m

output:
  format: checkstyle:reports/checkstyle.xml,colored-line-number

linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
  disable:
    - ireturn

linters-settings:
  exhaustruct:
    exclude:
      - ".*_test"
  paralleltest:
    ignore-missing: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
